// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7N07kKwKGlNrMDjo7bNPQo5HCZm1BO8A',
    appId: '1:85143890525:web:f7c207623f39febdebfbb4',
    messagingSenderId: '85143890525',
    projectId: 'product-manager-app-da74c',
    authDomain: 'product-manager-app-da74c.firebaseapp.com',
    storageBucket: 'product-manager-app-da74c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgDVSh_OIGhQLFoNgFRuTSvelt4ORZi6s',
    appId: '1:85143890525:android:a5b1482b814bd40cebfbb4',
    messagingSenderId: '85143890525',
    projectId: 'product-manager-app-da74c',
    storageBucket: 'product-manager-app-da74c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGnQJGulDYWbXr3hL0VRriMNUFkhAum8w',
    appId: '1:85143890525:ios:2009a268f2514450ebfbb4',
    messagingSenderId: '85143890525',
    projectId: 'product-manager-app-da74c',
    storageBucket: 'product-manager-app-da74c.firebasestorage.app',
    iosBundleId: 'com.example.productManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGnQJGulDYWbXr3hL0VRriMNUFkhAum8w',
    appId: '1:85143890525:ios:2009a268f2514450ebfbb4',
    messagingSenderId: '85143890525',
    projectId: 'product-manager-app-da74c',
    storageBucket: 'product-manager-app-da74c.firebasestorage.app',
    iosBundleId: 'com.example.productManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7N07kKwKGlNrMDjo7bNPQo5HCZm1BO8A',
    appId: '1:85143890525:web:97573a6828a8d90debfbb4',
    messagingSenderId: '85143890525',
    projectId: 'product-manager-app-da74c',
    authDomain: 'product-manager-app-da74c.firebaseapp.com',
    storageBucket: 'product-manager-app-da74c.firebasestorage.app',
  );

}